language: node_js
node_js:
- '8'
script: yarn gulp
deploy:
  provider: script
  skip_cleanup: true
  script: yarn send
env:
  global:
  - secure: TmuNaE1hLQoBMrKHVQeznatLfHNf0FyE2VKeiaOWI9OLVhtAh5zEz9uWsPxakXjg+abZgHFgs2qQjjxEapOhFAOAwbnGnQiijjHfbaNQ+ixjl9NvKQmrRz8D122CIbpce7ttW5XesaKt30TbMlrRolxwWA/fHNDqhRK9lZZCO21sqcctClMlgPhjDH7MEwPwvWQo+6KG6Is42EMOdYogKycXCrfEBYy4VyXu0J/HsWQVfee/f2ExewDZjHZaZ2ct64JQGXu2ovPiLt/1XTpdGXb94dXQpppbCuaw2PiNAHmE74XaqXAUyz8ep9u5gY8Q3sbSG7ezzpfY10XE5urZ5ASoaQuCu1SpsaGOE7UUKrOqKi+S0Q4x1Lz8hY/VAI8rsbBeNaIHQlfR7QZQSNw0QSclQaeCiBZFbBEkicP23e+i3YhTenNiowxHm8SanyGDsa6cMhKUEJlAeEswVvoazc7Mgwr1hclSiz9WC78ojRYpfzi/WrY7ilv6ldvPumF/lff5R0TPZPVvN83/mamF8GG+H3CoyQphPfmYo5bwA25WPjbVzp2J6xMAVQkSYTI+SSXAHjaiCb2BqWSC4WZ9gGtsoBktKSlkVUHx9OG/J0SCCg+NXU6BCLpblftu8lVNndhhO3VMZSVA2fdjrF8NXwe1VA4hTqrjFeMkvFujDfA=
