language: node_js

node_js:
  - "8"

script: yarn gulp

deploy:
  provider: script
  skip_cleanup: true
  script: yarn send

env:
  global:
    secure: pMzXjo3QExU+fo2Qa1tPNSzBr55ttHhg4DDzxpIAmQ9CX5+4DQ/nxcWiPQBQjVn4fJilGRDC6VLHrbc0MOu0Re1scemD1QZLX8JfTu4KSa6N/qpz8ep+y4TA3LDD9g9SVWRX1AtdontC+qTEHSQ04gcPfcLKuUZAi288kUJBy32Q8xUiOtvsxY40lsyImGV3cGvFk9RPguT6Y2w3AYMJ17rl22yRL0bR+onQrexEBWDfApYgk9Lbb/3ISFI5gyBy3hxQgCPa10GjpnLy8HihI5zfESglMxRNNhA6ld7ibscYRSTECsRLjln/9ZyX5bjyox5OD/3wgpLy0qhCnrkcRbxhCII83VQpN8EmtNFGpuWl9VrxV+Rcd99JISbL7n0ATiYWrKJAThK/rghWq0Ig96soXM0C3z6F2Lx9VAIi/YUdS8H9oV/SS8drN8tMX0jcI2BzmdPttpFOKzqJRemq4UH3wrF5a2rRFmztmy9jSk4j91htRbJU1YPixjluUgmsuxMGVC8XJhjPs6yiBgIrw9wOAKQjmNqV0zVv323TIKnbxPa/x+F9wPFsXnhHRlbhB1pb38haV0/Ogsbpg/ODD0JTeTzRiPFQzeaLD10ajHv4B+0JUiwtqWT/JSAef28DxRgAQVtDOO3v1xuI5nd5o8mnEPlP5MOp/HuWnWftqEM=
