name: release
on:
  release:
    types:
      - created
jobs:
  release:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn gulp
      - name: Upload to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.tdesktop-theme
      - name: Send to Telegram
        run: yarn send
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
